---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    author: sbg
spec:
  type: loadBalancer
  ports:
    - targetPorts: 80
      port: 80
 selector:
   name: result-app-service
   author: sbg
...