---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    author: sbg
spec:
  type: loadBalancer
  ports:
    - taegetPort: 80
      port: 80
  selector:
    name: voting-app-service
    author: sbg
...
